name: Build AX3600 Robimarko
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/robimarko/openwrt
  REPO_BRANCH: ipq807x-5.15-pr
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: AX3600.config
  SETUP_SH: setup.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Clone source code
        format: markdown

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Update feeds
        format: markdown

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Install feeds
        format: markdown

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Load custom configurations
        format: markdown

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $SETUP_SH
        cd openwrt
        $GITHUB_WORKSPACE/$SETUP_SH

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Download package
        format: markdown

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Build tools
        format: markdown

    - name: Build tools
      run: |
        cd openwrt
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Build toolchain
        format: markdown

    - name: Build toolchain
      run: |
        cd openwrt
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Build target images
        format: markdown

    - name: Build target images
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j2 || make -j2 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Remove packages
      id: remove
      if: (!cancelled())
      run: |
        rm -rf openwrt/bin/targets/ipq807x/generic/packages
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "last_commit=$(git -C openwrt rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        echo "release_date=$(date +"%Y/%m/%d")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: notif process
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.repository.name }}: Generate release
        format: markdown

    - name: Create a release
      uses: ncipollo/release-action@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      with:
        name: "Xiaomi AX3600 update ${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}"
        tag: "ax3600-openwrt-${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}"
        generateReleaseNotes: false
        makeLatest: true
        artifacts: openwrt/bin/targets/ipq807x/generic/*

    - name: Send to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ ${{ github.event.repository.name }}
          OpenWrt for Xiaomi AX3600 has been update
          Updated: ${{ steps.tag.outputs.release_date }}

          • Repo: ${{ env.REPO_URL }}
          • Branch: ${{ env.REPO_BRANCH }}
          • Hash: ${{ steps.tag.outputs.last_commit }}
          • Download: 
            [openwrt-ax3600-initramfs-factory.ubi](https://github.com/rendiix/AX3600-OpenWrt-Builder/releases/download/${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}/openwrt-ipq807x-generic-xiaomi\_ax3600-initramfs-factory.ubi)
            [openwrt-ax3600-initramfs-uImage.itb](https://github.com/rendiix/AX3600-OpenWrt-Builder/releases/download/${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}/openwrt-ipq807x-generic-xiaomi\_ax3600-initramfs-uImage.itb)
            [openwrt-ax3600-squashfs-factory.ubi](https://github.com/rendiix/AX3600-OpenWrt-Builder/releases/download/${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}/openwrt-ipq807x-generic-xiaomi\_ax3600-squashfs-factory.ubi)
            [openwrt-ax3600-squashfs-sysupgrade.bin](https://github.com/rendiix/AX3600-OpenWrt-Builder/releases/download/${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.last_commit }}/openwrt-ipq807x-generic-xiaomi\_ax3600-squashfs-sysupgrade.bin)
        format: markdown

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
